### ISSUE TITLE
UE 4.25.3 support for SDK v1.7.1

### ISSUE THREAD

**Issue by Shadpw2** [gaslightgames/UE4_EOS_Plugin#37]
SDK version 1.7 is no longer available to download, nor is unreal engine version 4.25.0-4.25.2. I’ve tried auto rebuilding the plugin but it fails to build. Any support to fix this would be much appreciated!

**Comment by fastlorisstudios** [comment]
4.25.3 build just fine, as that's what I use.
Will have to check on the 1.7.1, but the last minor revision (1.6 -> 1.6.1, iirc) build just fine, so everything _should_ be OK. I've been largely working on client/contract work, so had zero free time, but my aim to jump back on this on Friday (4th Sept) this week.

**Comment by fastlorisstudios** [comment]
As suspected, integrating 1.7.1 instead of 1.7 illicited no additional changes.

I downloaded the 1.7.1 SDK zip. Removed my old Bin, Lib and Source folders. Then extracted the new ones from the Zip to the correct location. Went up to the EOS Sample .uproject, right clicked and "Generate Visual Studio Project Files."
Then over in Visual Studio, performed a full Rebuild (so as to clean everything and ensure I've no stale files)... everything completed successfully.
