### ISSUE TITLE
Crash in PIE when initializing the module multiple times in separate sessions

### ISSUE THREAD

**Issue by HiIAmMoot** [gaslightgames/UE4_EOS_Plugin#5]
I've noticed a crash that occurs when you are in PIE and try to initialize the EOS while having done so before in a previous PIE session.

Steps to reproduce:
1. Start PIE
2. Enable EOS module
3. Disable EOS module
4. End PIE
5. Start PIE again
6. Enable EOS module

**Comment by fastlorisstudios** [comment]
Appreciate the repro steps and, sadly, 100% repro'd my end.
I'm on it :-)

I was also able to get a crash if I Shutdown the module, before a successful Init and then tried to init again.

**Comment by fastlorisstudios** [comment]
According to the docs, any calls after Shutdown (from what I can gather, even further Init calls) will result in "Undefined Behaviour."  The output is saying that it cannot find the target function, so Shutdown is completely tearing down everything, including access to the DLL.

I've put some guards in place so that if the EOS was shutdown, then the Plugin wont let you Init nor attempt to shut it down again.  Will have to think differently as to how to aid this in PIE, as the Editor will still be keeping open access to the DLLs.  Once I get this working properly, in the Editor, when using "Standalone," I'll revisit the approach for solving PIE usage.

**Comment by HiIAmMoot** [comment]
This may help. Might be good to completely disable any EOS usage in PIE. https://answers.unrealengine.com/questions/222975/how-can-i-tell-if-im-in-standalone-or-new-editor-w.html

**Comment by fastlorisstudios** [comment]
> This may help. Might be good to completely disable any EOS usage in PIE. https://answers.unrealengine.com/questions/222975/how-can-i-tell-if-im-in-standalone-or-new-editor-w.html

Sounds like a plan.  From what that link was suggesting, a Standalone doesn't get classed as PIE on WorldType, so should mean everything will work as expected.

I've also put various guards in place, so one cannot init multiple times, shutdown multiple times, nor init after a shutdown (as that results in Undefined), that was in [this commit](https://github.com/gaslightgames/UE4_EOS_Plugin/commit/3183d13b1aea5d9aaaf82468301dc778ced1f20f).
I'm going to make the PIE a new issue, easier to track :-)
